### ISSUE TITLE
每次跳转到指定activity觉得有点不合理

### ISSUE THREAD

**Issue by samhaus** [linkaipeng/OkNetworkMonitor#3]
可不可以参考LeakCanery那种

**Comment by linkaipeng** [comment]
嗯嗯，可以，我后续看一下

**Comment by linkaipeng** [comment]
已经在此 commit 添加：[25509d6](https://github.com/linkaipeng/OkNetworkMonitor/commit/25509d631a3cd0cbacc0f5277bedf44ae9c99872)
