### ISSUE TITLE
希望添加生成CURL的功能

### ISSUE THREAD

**Issue by madroidmaq** [linkaipeng/OkNetworkMonitor#5]
可以参考

https://gist.github.com/jgilfelt/42d1c020cc66d3f0a0d7
https://gist.github.com/terrakok/8e435c1473da4c21e1f4299a21e5e6e9

**Comment by MaAnQing** [comment]
可以参考

 https://gist.github.com/jgilfelt/42d1c020cc66d3f0a0d7
 https://gist.github.com/terrakok/8e435c1473da4c21e1f4299a21e5e6e9

**Comment by linkaipeng** [comment]
Added. https://github.com/linkaipeng/OkNetworkMonitor/commit/ea7557fdc19b7f407e38d701ccb118ebb4fde863
